@startuml
'https://plantuml.com/sequence-diagram

autonumber
终端点餐页面->终端点餐: 提交订单
终端点餐 -> mqtt服务器: 发送订单指令
mqtt服务器 -> 阿里云服务器: 发送订单，阿里云制作订单
阿里云服务器->腾讯支付: 发送native支付请求

阿里云服务器 <-- 腾讯支付: 异步发送微信支付二维码url
mqtt服务器 <-- 阿里云服务器: 异步发送微信支付二维码url
终端点餐 <-- mqtt服务器:监听到微信支付二维码url
终端点餐页面<--终端点餐: 拿到微信支付二维码url,生成并展示
@enduml