server:
  port: 8080 # 服务端口

spring:
  web:
    resources:
      static-locations: classpath:/static/ # 静态资源位置
  application:
    name: junchuang # 应用名称
  jackson:
    serialization:
      INDENT_OUTPUT: true # 是否格式化 JSON 输出
  redis:
    host: localhost # Redis 主机地址
    port: 6379 # Redis 端口

mqtt:
  url: tcp://${url}:1884 # MQTT 服务器 URL
  username: admin # MQTT 用户名
  password: 123 # MQTT 密码
  send_id: "send_${machineCode}" # 发送 ID
  listen_id: "listen_${machineCode}" # 监听 ID

# 日志配置（仅在 Windows 有效）
logging:
  config: classpath:logbak.xml # 日志配置文件路径

# 机器码
machineCode: A000001 # 用于标识设备的唯一代码

# URL 配置
url: www.zjngic.com # 服务器地址

# 本机 IP 配置
ip:
  local: 192.168.1.2 # 本机 IP 地址
  nettyPort: 5555 # Netty 端口
  io: 192.168.1.3 # IO 设备 IP
  relay: 192.168.1.4 # 中继设备 IP
  siloWeighBoxIp: 192.168.1.7 # 称重箱设备 IP
  send485Order: 192.168.1.5 # 发送 485 命令设备 IP
  receive485Signal: 192.168.1.6 # 接收 485 信号设备 IP
  ducuIp: 192.168.1.10 # DUCU 设备 IP
  ducuPort: 2000 # DUCU 设备端口

# 机器人状态配置
robot:
  reset: false # 是否重置机器人
  bowlPickupSuccess: false # 是否完成取碗
  soupOutSuccess: false # 是否完成出汤
  beefReady: false # 是否牛肉准备完成
  beefStorageAdded: false # 是否牛肉储存完成
  steamReady: false # 是否蒸汽准备完成
  steamAdded: false # 是否添加蒸汽完成
  seasoningAdded: false # 是否添加调料完成
  soupAdded: false # 是否添加汤完成

# 出餐完成状态
#ejectionIsComplete: false # 是否完成出餐

# 各设备在线状态
client:
  docuOnLine: false # DUCU 是否在线
  send485Order: false # 发送 485 命令设备是否在线
  receive485Singal: false # 接收 485 信号设备是否在线
  iOdevice: false # IO 设备是否在线
  relayDevice: false # 中继设备是否在线

# 公共变量参数
pub:
  orderNumber: 0 # 当前订单编号
  allDevicesConnectedStatus: false # 是否所有设备连接状态正常
  deviceSelfCheckComplete: false # 设备是否完成自检
  soupTemperatureValue: 0.0 # 汤温度值
  calculateWeight:  # 是否计算重量
  thereIsABowlAtTheServingWindow:  # 出餐窗口是否有碗
  theBowlWasNotTakenFromTheServingWindow:  # 碗是否未从出餐窗口取走
  currentFanBinNumber: 0 # 当前粉丝料仓编号
  areTheFansReady: false # 粉丝是否准备好
  dishesAreReady: false # 菜品是否准备好
  servingDishesCompleted: false # 出菜是否完成

# 数据配置
data:
  beef10: 10 # 牛肉 10 克
  beef15: 15 # 牛肉 15 克
  beef20: 20 # 牛肉 20 克
  cilantro: 10 # 香菜克数
  choppedGreenOnion: 10 # 葱花克数
  soupExtractionTime: 8 # 汤提取时间（秒）
  vibratorTime: 5 # 振动器工作时间（秒）
  soupHeatingTemperature: 120 # 汤加热温度（℃）
  soupInsulationTemperature: 80 # 汤保温温度（℃）
  steamAdditionTimeSeconds: 10 # 加蒸汽时间（秒）
  soupExhaustTime: 10 # 汤排气时间（秒）
  ladleWalkingDistanceValue: 1900 # 菜勺走动距离值
  ladleDishDumpingRotationValue: 1300 # 菜勺倒菜转动值
  fanPushRodThrustDistanceValue: 1000 # 粉丝推杆推动距离值
